const CartActionTypes = {
    FETCH_CART_SUCCESS: 'FETCH_CART_SUCCESS',
    FETCH_CART_FAILURE: 'FETCH_CART_FAILURE',
    ADD_ITEM: 'ADD_ITEM',
    ADD_ITEM_WITH_COUNT: 'ADD_ITEM_WITH_COUNT',
    REMOVE_ITEM: 'REMOVE_ITEM',
    CLEAR_ITEM: 'CLEAR_ITEM',
    CLEAR_CART: 'CLEAR_CART'
};

export default CartActionTypes;

